# Report {.unnumbered}

## Goals
  In this proposal, we are hoping to investigate how usage of various social media differs by relationship status in addition to  several other questions. We will first determine what the most used social media app is and how long individuals spend on it. Then, we will investigate how that differs by gender and relationship status. Relationship status is a demographic that has rarely been explored as a variable in social media usage statistics. If relationship status is found to influence social media usage time, this could indicate an area for further research. Might, for example, the increased overall happiness of being in a relationship decrease average social media usage time?  Or, might divorced (or single) status lead to a decrease in overall happiness--resulting in an increased dependency on (and thus usage of) social media apps?  

## Data

Our data was acquired from the data repository site "Kaggle".  This dataset consists of usage patterns collected across eight social media platforms--including: Facebook, Pinterest, Reddit, Youtube, Discord, Instagram, Twitter, Snapchat.  There are 481 observations of 21 variables--including demographic questions. For the sake of simplicity, we renamed many of the variables in the dataset (often shortening them).


## Takeaways

Of the people surveyed, single individuals spent the most time using social media. Married and divorced individuals spent the least amount of time on social media sites, while individuals in a relationship had usage levels on par with single individuals. It is important to note, however, that there were very few divorced individuals who were surveyed (only six), so results concerning that demographic likely aren't as generalizable as for individuals who are single, married, or in a relationship.  This might be because married individuals have more responsibilities (household chores, children to take care of, etc.) meaning that they have the least amount of free time to spend on social media platforms.  Single individuals and those in relationships likely have fewer responsibilities and thus more time to spend on social media platforms.  

When considering gender-based splits in usage, we see that men use Discord, Reddit, and Twitter more, while Facebook, Instagram, Snapchat, TikTok, and Pinterest are used more by women.  Additionally, women spent overall more time on social media platforms than men.  The differences in usage by platform likely demonstrate a gender-based preference for different platforms and also might indicate something about gender relations on different platforms--i.e. whether there is any sort of sexist culture on a given platform.  The fact that women use social media platforms far more than men is fairly suprising and indicates an area for future research--to further investigate additional contributing factors. 


Overall, what do you want the audience to walk away with? What do you want them to understand about your data and research questions?!?

## Big Picture
How do the insights connect to answer your research question?
What improvements might someone make to your analysis?
Are there any limitations or weaknesses of your data / analysis?
